name: macOS Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-15-arm64
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    
    - name: Build
      run: |
        cd crates/mpsgraph-tools-rs
        cargo build --verbose
    
    - name: Run tests
      run: |
        cd crates/mpsgraph-tools-rs
        cargo test --verbose
    
